# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box_url = "https://fortishield.github.io/packages-dev/vms/ova/amznlinux-2.box"
  config.vm.box = "amznlinux-2"
  config.vm.hostname = "fortishield-server"
  config.vm.provider "virtualbox" do |vb|
    vb.name = "vm_fortishield"
    vb.memory = "8192"
    vb.cpus = "4"
  end

  config.ssh.username = "fortishield-user"
  config.ssh.password = "fortishield"
  config.ssh.insert_key = true

  # Synced folder configuration
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.synced_folder ".", "/tmp", type: "rsync", :rsync__exclude => ['output']

  # Provision stage
  config.vm.provision :shell, path: "provision.sh", :args => "#{ENV['PACKAGES_REPOSITORY']} #{ENV['DEBUG']}"

end
